### ISSUE TITLE
how to convert output grasp from inference.py to real-world coordinate system

### ISSUE THREAD

**Issue by xlim1996** [NVlabs/contact_graspnet#23] opened 2022-07-12 08:59 UTC
Hi,@MartinSmeyer
I have a question: how to convert output grasp from inference.py to the real-world coordinate system? I use the following code to calculate the position from pred_grasps_cam,but the result seem incorrect. So I'm wondering if the matrix from pred_grasps_cam  contains position and rotation information about the coordinates relative to the object what it want to grasp, or the coordinates actually in the image, or the coordinates actually in real-world?
````python
def rotationMatrixToEulerAngles(R) :

    if R[1,0]>0.998:
        x= 0
        y=math.pi/2
        z=math.atan2(R[0, 2], R[2, 2])
    elif R[1, 0] <-0.998:
        x=0
        y=-math.pi / 2
        z = math.atan2(R[0, 2], R[2, 2])
    else:
        x = math.atan2(-R[1,2],R[1,1])
        y = math.asin(R[1,0])
        z = math.atan2(-R[2,0],R[0,0])

    return x,y,z

def getRotationAndPosition(transformation):
    assert transformation.shape[0] ==4 and transformation.shape[1] ==4 ,"shape error"
    x = transformation[0,3]
    y= transformation[1,3]
    z = transformation[2,3]
    x_r,y_r,z_r =rotationMatrixToEulerAngles(transformation[0:3,0:3])
    return x, y, z, x_r,y_r,z_r
````

**Comment by MartinSmeyer** [comment] 2022-07-12 09:16
Hey @xlim1996,

The grasps are predicted in OpenCV coordinates, i.e. not with respect to the object (we don't have the coordinate frame of unknown objects) but wrt. the camera. There are no "real-world coordinates" you always need to define a coordinate system. In our case we want the grasps in the camera coordinate system and we use the conventional opencv axes. Here is an image describing the conventions:

![image](https://user-images.githubusercontent.com/18601778/178454295-95c331b1-79df-48b2-ac5c-855bb36804f4.png)

If you want to grasp an object with a robot, you need to transform the grasps from opencv camera coordinates to your robot base coordinate system. For that you need to calibrate the camera to the robot, either by mounting the sensor on the wrist or using a calibration pattern.

Duplicate of #14

**Comment by xlim1996** [comment] 2022-07-12 10:41
Hi,
Thanks for your reply and for providing the detail about the different coordinate systems.
I will try it by myself.

**Closed** 2022-07-28 12:24 UTC
